{
 "title": "NATS Cluster Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(nats_connections)" }
   ]
  },
  {
   "title": "Slow Consumers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "sum(nats_slow_consumers)" }
   ]
  },
  {
   "title": "In/Out Messages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "sum(rate(nats_in_msgs[5m]))", "legendFormat": "In" },
    { "expr": "sum(rate(nats_out_msgs[5m]))", "legendFormat": "Out" }
   ]
  }
 ]
}